"""
Phase 2: FastAPI backend for the oil crisis simulation platform.

Endpoints, matching the original project spec plus the refinery/GIS layer:
    POST /api/v1/simulate                    -- run a what-if crisis scenario,
                                                  get a predicted price change,
                                                  EV/lithium feasibility, and a
                                                  plain-language explanation
    GET  /api/v1/conflicts                    -- list historical events with
                                                  coordinates, for the globe
    GET  /api/v1/refineries                   -- list refinery/export hubs
                                                  with coordinates + capacity,
                                                  for the globe
    GET  /api/v1/refineries/at-risk/{chokepoint} -- capacity dependent on one
                                                  chokepoint (Hormuz, Suez,
                                                  Malacca, Bab el-Mandeb)
    GET  /api/v1/routes/{chokepoint}          -- bypass routes for one
                                                  chokepoint (real pipelines/
                                                  alternate straits), and how
                                                  much at-risk capacity they
                                                  can actually absorb

Run this with:  uvicorn main:app --reload
Then open:      http://127.0.0.1:8000/docs
(that /docs page is auto-generated by FastAPI -- it gives you a free
interactive UI to test both endpoints without writing any frontend code yet)
"""

import asyncio
import json
import logging
from contextlib import asynccontextmanager

from dotenv import load_dotenv

load_dotenv()  # must run before any module below reads ANTHROPIC_API_KEY / ALPHA_VANTAGE_API_KEY

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from ev_lithium import DEFAULT_GLOBAL_DAILY_CRUDE_PRODUCTION_BBL, supply_shock_to_ev_feasibility
from refineries import capacity_at_risk_bpd, capacity_at_risk_pct_of_global, load_refineries, refineries_at_chokepoint
from routing import load_bypass_routes, recommend_reroute

from news import db as news_db
from news import price_engine
from news.classify import classify_article
from news.fixtures import FIXTURES
from news.ingestion import url_hash
from news.models import Article, ClassifiedEvent
from news.poller import poll_loop
from news.relevance import is_relevant

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")


@asynccontextmanager
async def lifespan(app: FastAPI):
    news_db.init_db()
    poller_task = asyncio.create_task(poll_loop())
    yield
    poller_task.cancel()


app = FastAPI(title="Oil Crisis Simulation API", lifespan=lifespan)

# Allow a frontend running on a different port (e.g. React on :3000) to call
# this API during development. Tighten this before deploying publicly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Load the Phase 1 artifacts once, when the server starts (not per-request --
# that would be slow and pointless, since nothing in these files changes)
# ---------------------------------------------------------------------------
baseline = joblib.load("data/price_surge_baseline.joblib")
ELASTICITY = baseline["elasticity"]

events_df = pd.read_csv("data/events.csv", parse_dates=["event_date"])
refineries_df = load_refineries()
bypass_routes_df = load_bypass_routes()

# Chokepoints this platform tracks -- must match CHOKEPOINT_COORDS keys.
KNOWN_CHOKEPOINTS = {"hormuz", "bab el-mandeb", "suez", "malacca"}

# Rough coordinates for the named chokepoints in your events table.
# (Approximate midpoints of each strait/canal -- good enough for globe
# plotting; refine later if you need shipping-lane-accurate positions.)
CHOKEPOINT_COORDS = {
    "hormuz": {"lat": 26.57, "lng": 56.25},
    "bab el-mandeb": {"lat": 12.58, "lng": 43.32},
    "suez": {"lat": 30.44, "lng": 32.34},
    "malacca": {"lat": 2.5, "lng": 101.3},
}


# ---------------------------------------------------------------------------
# Request / response schemas
# Pydantic (the library these classes use) automatically validates incoming
# JSON against these definitions -- if a request is missing a field or sends
# a string where a number is expected, FastAPI rejects it automatically,
# before your code even runs.
# ---------------------------------------------------------------------------
class SimulateRequest(BaseModel):
    supply_loss_pct: float = Field(..., ge=-20, le=20, description="Percent of global crude supply lost (negative = surplus added)")
    conflict_intensity: float = Field(..., ge=0, le=10, description="0 (none) to 10 (full-scale war)")
    detour_days: float = Field(0, ge=0, description="Extra shipping days from rerouting, if applicable")
    demand_change_pct: float = Field(0, ge=-50, le=50, description="Percent change in global demand (negative = demand drop)")


class EvFeasibility(BaseModel):
    barrels_per_day_lost: float
    gasoline_vehicle_years_displaced: float
    lithium_tonnes_required: float
    lithium_supply_ratio: float = Field(
        ..., description="lithium_tonnes_required / one year of global lithium production"
    )
    explanation: str


class SimulateResponse(BaseModel):
    predicted_price_change_pct: float
    explanation: str
    model_used: str
    ev_feasibility: EvFeasibility


class ConflictEvent(BaseModel):
    name: str
    event_date: str
    chokepoint: str
    conflict_intensity: float
    supply_loss_pct: float
    lat: float | None = None
    lng: float | None = None


class RefineryHub(BaseModel):
    name: str
    country: str
    lat: float
    lng: float
    capacity_bpd: float
    hub_type: str
    nearest_chokepoint: str
    notes: str


class ChokepointRisk(BaseModel):
    chokepoint: str
    capacity_at_risk_bpd: float
    pct_of_global_daily_production: float
    affected_hubs: list[str]


class BypassOption(BaseModel):
    via: str
    route_type: str
    capacity_bpd: float | None
    extra_transit_days: float
    notes: str


class RouteRecommendation(BaseModel):
    chokepoint: str
    capacity_at_risk_bpd: float
    affected_hubs: list[str]
    bypass_options: list[BypassOption]
    fast_bypass_capacity_bpd: float
    uncovered_capacity_bpd: float
    explanation: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.post("/api/v1/simulate", response_model=SimulateResponse)
def simulate(req: SimulateRequest):
    """
    Run a what-if scenario. Currently uses the Phase 1 baseline formula
    (confirmed in Phase 1 testing to outperform a trained model on the
    available 21-event dataset) -- see PHASE1_SUMMARY.md for why.
    """
    predicted_pct = req.supply_loss_pct / ELASTICITY

    # Plain-language explanation, built from what Phase 1 actually found --
    # not a generic message. This is where the "explanation" part of your
    # dashboard goal comes from.
    parts = []
    if req.supply_loss_pct > 0:
        parts.append(f"A {req.supply_loss_pct:.1f}% loss of global supply, under standard "
                      f"short-run demand inelasticity (Ed = -{ELASTICITY}), implies roughly a "
                      f"{predicted_pct:.1f}% price increase.")
    elif req.supply_loss_pct < 0:
        parts.append(f"A {abs(req.supply_loss_pct):.1f}% increase in supply implies roughly a "
                      f"{abs(predicted_pct):.1f}% price decrease.")
    else:
        parts.append("No direct supply change specified.")

    if req.demand_change_pct != 0:
        parts.append(f"Note: this scenario also involves a {req.demand_change_pct:.1f}% demand "
                      f"change. Phase 1 testing found demand-driven events (like 2020 COVID or "
                      f"2008) behave differently from pure supply shocks, and this formula does "
                      f"not yet account for that -- treat this prediction as less reliable when "
                      f"demand_change_pct is far from zero.")

    if req.conflict_intensity >= 7 and req.supply_loss_pct < 2:
        parts.append(f"Conflict intensity is high ({req.conflict_intensity}) but modeled supply "
                      f"loss is low -- historically (e.g. the 2025 Israel-Iran war), this pattern "
                      f"produces a real but short-lived price spike that fades once markets "
                      f"confirm no physical disruption occurred.")

    # Independently of the crude-price formula above: the news pipeline's
    # lithium_supply_index (news/price_engine.py, nudged by classified
    # ev_lithium_supply events) feeds straight into this EV feasibility
    # calculation, the exact same way chokepoint_disruption events feed
    # the simulated crude price -- see ev_lithium.py's docstring for the
    # index's meaning. Defaults to 1.0 (no-op) until a real/fixture
    # ev_lithium_supply event has actually fired.
    lithium_supply_index = price_engine.get_state()["lithium_supply_index"]
    ev = supply_shock_to_ev_feasibility(req.supply_loss_pct, lithium_supply_index=lithium_supply_index)

    return SimulateResponse(
        predicted_price_change_pct=round(predicted_pct, 2),
        explanation=" ".join(parts),
        model_used="elasticity_formula_baseline",
        ev_feasibility=EvFeasibility(
            barrels_per_day_lost=round(ev.barrels_per_day_lost, 0),
            gasoline_vehicle_years_displaced=round(ev.equivalent.gasoline_vehicle_years_displaced, 0),
            lithium_tonnes_required=round(ev.equivalent.lithium_tonnes_required, 0),
            lithium_supply_ratio=round(ev.lithium_supply_ratio, 3),
            explanation=ev.explanation,
        ),
    )


def _chokepoint_coords_for(chokepoint: str) -> dict:
    return CHOKEPOINT_COORDS.get(str(chokepoint).lower(), {"lat": None, "lng": None})


def _price_event_to_conflict_event(row: dict) -> ConflictEvent:
    """Reshapes one news-pipeline price_events row into the SAME
    ConflictEvent schema the static events.csv rows use (project brief
    section 5: reuse the existing event schema, don't create a second,
    parallel history store). conflict_intensity and supply_loss_pct are
    DERIVED, not independently chosen -- supply_loss_pct is backed out of
    the actual simulated price move via the same ELASTICITY the rest of
    this app already uses (predicted_pct = supply_loss_pct / ELASTICITY,
    inverted here), so this stays internally consistent with /api/v1/simulate
    rather than inventing a third, disconnected scale."""
    chokepoints = json.loads(row["chokepoints_json"])
    chokepoint = chokepoints[0] if chokepoints else "none"
    coords = _chokepoint_coords_for(chokepoint)

    pct_change = row["price_pct_change"] or 0.0
    supply_loss_pct = round(pct_change * ELASTICITY, 2)
    conflict_intensity = round(max(0.0, min(10.0, abs(row["severity"]) * row["confidence"] * 12)), 1)

    return ConflictEvent(
        name=f"{row['summary']} [SIMULATED, {row['classifier_used']}]",
        event_date=row["occurred_at"][:10],
        chokepoint=chokepoint,
        conflict_intensity=conflict_intensity,
        supply_loss_pct=supply_loss_pct,
        lat=coords["lat"],
        lng=coords["lng"],
    )


@app.get("/api/v1/conflicts", response_model=list[ConflictEvent])
def get_conflicts():
    """Returns all historical events with coordinates where available --
    the static dataset (events.csv) UNIONED with live, news-driven events
    that actually moved the simulated crude price (news/price_engine.py).
    Live entries are clearly tagged '[SIMULATED, <classifier>]' in their
    name so they're never mistaken for the real historical record."""
    results = []
    for _, row in events_df.iterrows():
        coords = _chokepoint_coords_for(row["chokepoint"])
        results.append(ConflictEvent(
            name=row["name"],
            event_date=row["event_date"].strftime("%Y-%m-%d"),
            chokepoint=row["chokepoint"],
            conflict_intensity=row["conflict_intensity"],
            supply_loss_pct=row["supply_loss_pct"],
            lat=coords["lat"],
            lng=coords["lng"],
        ))

    for row in news_db.crude_price_events_for_chart():
        results.append(_price_event_to_conflict_event(row))

    return results


@app.get("/api/v1/refineries", response_model=list[RefineryHub])
def get_refineries():
    """Returns all refinery/export-hub locations and capacities for the globe."""
    return [
        RefineryHub(
            name=row["name"],
            country=row["country"],
            lat=row["lat"],
            lng=row["lng"],
            capacity_bpd=row["capacity_bpd"],
            hub_type=row["hub_type"],
            nearest_chokepoint=row["nearest_chokepoint"],
            notes=row["notes"],
        )
        for _, row in refineries_df.iterrows()
    ]


@app.get("/api/v1/refineries/at-risk/{chokepoint}", response_model=ChokepointRisk)
def get_chokepoint_risk(chokepoint: str):
    """
    Total refining/export capacity dependent on one chokepoint (Hormuz,
    Suez, Malacca, Bab el-Mandeb) -- e.g. if Hormuz were blockaded, this
    is how much capacity, and which named hubs, would be cut off.
    """
    if chokepoint.lower() not in KNOWN_CHOKEPOINTS:
        raise HTTPException(status_code=404, detail=f"Unknown chokepoint '{chokepoint}'. Known: {sorted(KNOWN_CHOKEPOINTS)}")

    at_risk_df = refineries_at_chokepoint(refineries_df, chokepoint)
    capacity = capacity_at_risk_bpd(refineries_df, chokepoint)
    pct = capacity_at_risk_pct_of_global(refineries_df, chokepoint, DEFAULT_GLOBAL_DAILY_CRUDE_PRODUCTION_BBL)

    return ChokepointRisk(
        chokepoint=chokepoint,
        capacity_at_risk_bpd=round(capacity, 0),
        pct_of_global_daily_production=round(pct, 4),
        affected_hubs=list(at_risk_df["name"]),
    )


@app.get("/api/v1/routes/{chokepoint}", response_model=RouteRecommendation)
def get_route_recommendation(chokepoint: str):
    """
    Documented bypass routes for one chokepoint (real pipelines like
    Petroline/ADCOP/SUMED, or alternate straits like Lombok/Sunda), and how
    much of that chokepoint's at-risk capacity they can actually absorb vs
    what's left with only the slow Cape-of-Good-Hope option. See
    routing.py's KNOWN SIMPLIFICATION note: bypass capacity is pooled per
    chokepoint, not matched to which specific hub's crude it serves.
    """
    if chokepoint.lower() not in KNOWN_CHOKEPOINTS:
        raise HTTPException(status_code=404, detail=f"Unknown chokepoint '{chokepoint}'. Known: {sorted(KNOWN_CHOKEPOINTS)}")

    result = recommend_reroute(refineries_df, bypass_routes_df, chokepoint)

    return RouteRecommendation(
        chokepoint=result.chokepoint,
        capacity_at_risk_bpd=round(result.capacity_at_risk_bpd, 0),
        affected_hubs=result.affected_hubs,
        bypass_options=[
            BypassOption(
                via=o.via,
                route_type=o.route_type,
                capacity_bpd=o.capacity_bpd,
                extra_transit_days=o.extra_transit_days,
                notes=o.notes,
            )
            for o in result.bypass_options
        ],
        fast_bypass_capacity_bpd=round(result.fast_bypass_capacity_bpd, 0),
        uncovered_capacity_bpd=round(result.uncovered_capacity_bpd, 0),
        explanation=result.explanation,
    )


# ---------------------------------------------------------------------------
# News pipeline: ingestion -> classification (Claude when ANTHROPIC_API_KEY
# is set, else a rule-based fallback -- see news/classify.py) -> price
# simulation (news/price_engine.py) -> alert feed / historical chart union.
# The poller runs automatically via the lifespan handler above; these
# endpoints expose the resulting state and a manual test-injection path.
# ---------------------------------------------------------------------------
class TestInjectRequest(BaseModel):
    """Either set fixture_key (see news/fixtures.py for the available
    keys), or provide title/description/url directly for a one-off
    hand-written test article."""

    fixture_key: str | None = None
    title: str | None = None
    description: str | None = None
    url: str | None = None
    source: str = "manual-test"


class TestInjectResponse(BaseModel):
    article_title: str
    relevant: bool
    classifier_used: str | None = None
    classification: ClassifiedEvent | None = None
    skipped_reason: str | None = None
    price_state: dict | None = None


@app.post("/api/v1/news/test-inject", response_model=TestInjectResponse)
def test_inject_news(req: TestInjectRequest):
    """
    DEV-ONLY manual test-injection path (project brief section 6): feeds a
    fixture or hand-written article straight into the relevance ->
    classification -> price-engine pipeline, so the whole flow can be
    verified without waiting for real news. Not meant to be exposed
    outside local development.
    """
    if req.fixture_key:
        if req.fixture_key not in FIXTURES:
            raise HTTPException(status_code=404, detail=f"Unknown fixture_key. Known: {sorted(FIXTURES)}")
        article = FIXTURES[req.fixture_key]
    elif req.title and req.description and req.url:
        article = Article(title=req.title, description=req.description, url=req.url, source=req.source, published_at="")
    else:
        raise HTTPException(status_code=400, detail="Provide either fixture_key or title+description+url")

    if not is_relevant(article.title, article.description):
        news_db.record_skipped(url_hash(article.url), article, reason="skipped_not_relevant")
        return TestInjectResponse(article_title=article.title, relevant=False, skipped_reason="skipped_not_relevant")

    try:
        event, classifier_used = classify_article(article)
    except Exception as e:
        # e.g. the Claude path is active but the Anthropic API itself is
        # down/erroring -- a clear 503 beats an opaque 500.
        raise HTTPException(status_code=503, detail=str(e))

    news_db.record_classification(url_hash(article.url), article, event, classifier_used)
    price_state = price_engine.apply_event(article, event, classifier_used)

    return TestInjectResponse(
        article_title=article.title,
        relevant=True,
        classifier_used=classifier_used,
        classification=event,
        price_state=price_state,
    )


@app.get("/api/v1/news/recent")
def get_recent_news_classifications(limit: int = 50):
    """Audit log: every classified article, newest first -- raw article
    fields alongside the classification that was derived from it."""
    return news_db.recent_classifications(limit=limit)


@app.get("/api/v1/news/price")
def get_simulated_price():
    """Current simulated crude price + EV/lithium supply index. ALWAYS a
    simulation calibrated off classified news, never a live market quote
    -- see news/price_engine.py's docstring."""
    state = price_engine.get_state()
    return {**state, "is_simulation": True}


@app.get("/api/v1/news/alerts")
def get_news_alerts(limit: int = 50):
    """Live alert feed data: every event that actually moved the
    simulated price or lithium index, newest first."""
    return news_db.recent_price_events(limit=limit)


@app.get("/")
def root():
    return {"status": "ok", "docs": "/docs"}
